export const allVendors = {
  venue: {
    title: "Venue",
    icon: "🏛️",
    items: [
      {
        id: "v12",
        name: "Local Park Gazebo",
        specialty: "Simple, public space for small gatherings.",
        price: "₹1,500",
        cost: 1500,
        eventType: ["gathering"],
        contact: "contact@localpark.com",
      },
      {
        id: "v13",
        name: "University Auditorium",
        specialty: "Basic, functional space for talks or small events.",
        price: "₹4,000",
        cost: 4000,
        eventType: ["corporate", "gathering"],
        contact: "events@university.edu",
      },
      {
        id: "v9",
        name: "Park Pavilion",
        specialty: "Budget-friendly, open-air space for casual events.",
        price: "₹6,000",
        cost: 6000,
        eventType: ["party", "gathering"],
        contact: "contact@parkpavilion.com",
      },
      {
        id: "v5",
        name: "Community Hall",
        specialty: "Affordable and spacious for local gatherings.",
        price: "₹8,000",
        cost: 8000,
        eventType: ["party", "gathering"],
        contact: "contact@communityhall.com",
      },
      {
        id: "v14",
        name: "Celebration Hall",
        specialty: "A step-up from a basic hall, with better amenities.",
        price: "₹28,000",
        cost: 28000,
        eventType: ["party", "gathering", "wedding"],
        contact: "contact@celebrationhall.com",
      },
      {
        id: "v15",
        name: "The Cozy Nook Hall",
        specialty: "Perfect for intimate parties and small weddings.",
        price: "₹40,000",
        cost: 40000,
        eventType: ["party", "wedding", "gathering"],
        contact: "contact@cozynook.com",
      },
      {
        id: "v6",
        name: "SkyLounge Rooftop",
        specialty: "Chic city views for modern parties.",
        price: "₹22,000",
        cost: 22000,
        eventType: ["corporate", "party"],
        contact: "events@skylounge.com",
      },
      {
        id: "v2",
        name: "Sunset Beach Club",
        specialty: "Casual beachside parties and gatherings.",
        price: "₹24,000",
        cost: 24000,
        eventType: ["wedding", "party", "gathering"],
        contact: "events@sunsetbeach.com",
      },
      {
        id: "v3",
        name: "Urban Loft Gallery",
        specialty: "Modern, artistic, and chic receptions.",
        price: "₹45,000",
        cost: 45000,
        eventType: ["corporate", "party"],
        contact: "bookings@urbanloft.com",
      },
      {
        id: "v10",
        name: "The Vineyard Estate",
        specialty: "Romantic vineyard setting for elegant weddings.",
        price: "₹75,000",
        cost: 75000,
        eventType: ["wedding"],
        contact: "events@vineyardestate.com",
      },
      {
        id: "v7",
        name: "Heritage Palace",
        specialty: "Royal and historic setting for grand weddings.",
        price: "₹85,000",
        cost: 85000,
        eventType: ["wedding"],
        contact: "palace@heritage.com",
      },
      {
        id: "v1",
        name: "The Grand Ballroom",
        specialty: "Luxury weddings and corporate events.",
        price: "₹120,000",
        cost: 120000,
        eventType: ["wedding", "corporate"],
        contact: "contact@grandballroom.com",
      },
      {
        id: "v8",
        name: "5-Star Convention Center",
        specialty: "All-inclusive packages for large corporate events.",
        price: "₹250,000",
        cost: 250000,
        eventType: ["corporate"],
        contact: "mice@5star.com",
      },
      {
        id: "v16",
        name: "The Emerald Gardens",
        specialty: "Expansive gardens for large, upscale events.",
        price: "₹450,000",
        cost: 450000,
        eventType: ["wedding", "corporate"],
        contact: "contact@emeraldgardens.com",
      },
      {
        id: "v17",
        name: "Serene Shores Retreat",
        specialty: "Exclusive lakeside property for private events.",
        price: "₹525,000",
        cost: 525000,
        eventType: ["wedding", "corporate"],
        contact: "contact@sereneshores.com",
      },
      {
        id: "v18",
        name: "Skyline Terrace",
        specialty: "Premium rooftop venue with panoramic city views.",
        price: "₹600,000",
        cost: 600000,
        eventType: ["wedding", "corporate"],
        contact: "contact@skylineterrace.com",
      },
      {
        id: "v11",
        name: "Private Island Resort",
        specialty: "Exclusive, ultimate luxury for once-in-a-lifetime events.",
        price: "₹800,000",
        cost: 800000,
        eventType: ["wedding"],
        contact: "bookings@privateisland.com",
      },
      {
        id: "v19",
        name: "The Zenith Palace",
        specialty: "The pinnacle of luxury venues for royalty-style events.",
        price: "₹1,000,000",
        cost: 1000000,
        eventType: ["wedding"],
        contact: "contact@zenithpalace.com",
      },
    ],
  },
  catering: {
    title: "Catering",
    icon: "🍽️",
    items: [
      {
        id: "c12",
        name: "Potluck Coordination",
        specialty: "We help organize and supplement your potluck.",
        price: "₹1,000",
        cost: 1000,
        eventType: ["gathering"],
        contact: "help@potluckpros.com",
      },
      {
        id: "c11",
        name: "Pizza Party Pack",
        specialty: "Bulk order of assorted pizzas and soft drinks.",
        price: "₹2,500",
        cost: 2500,
        eventType: ["party", "gathering"],
        contact: "orders@pizzaparty.com",
      },
      {
        id: "c9",
        name: "Taco Truck Fiesta",
        specialty: "Fun and casual, serving fresh tacos and nachos.",
        price: "₹4,000",
        cost: 4000,
        eventType: ["party", "gathering"],
        contact: "fiesta@tacotruck.com",
      },
      {
        id: "c5",
        name: "Local Delights",
        specialty: "Authentic regional street food style.",
        price: "₹5,000",
        cost: 5000,
        eventType: ["party", "gathering"],
        contact: "orders@localdelights.com",
      },
      {
        id: "c2",
        name: "Feast & Flame BBQ",
        specialty: "Authentic smokehouse BBQ catering.",
        price: "₹8,500",
        cost: 8500,
        eventType: ["party", "gathering"],
        contact: "catering@feastflame.com",
      },
      {
        id: "c13",
        name: "Mumbai Masala Carts",
        specialty: "Live stations for authentic Mumbai street food.",
        price: "₹25,000",
        cost: 25000,
        eventType: ["party", "wedding", "gathering"],
        contact: "contact@mumbaimasalacarts.com",
      },
      {
        id: "c3",
        name: "The Green Leaf",
        specialty: "Vegetarian and vegan gourmet meals.",
        price: "₹15,000",
        cost: 15000,
        eventType: ["wedding", "corporate", "gathering"],
        contact: "hello@thegreenleaf.com",
      },
      {
        id: "c6",
        name: "World Cuisine Buffet",
        specialty: "A lavish spread from around the globe.",
        price: "₹21,000",
        cost: 21000,
        eventType: ["wedding", "corporate"],
        contact: "info@worldcuisine.com",
      },
      {
        id: "c1",
        name: "Gourmet Bites",
        specialty: "Fusion cuisine with artistic presentation.",
        price: "₹30,000",
        cost: 30000,
        eventType: ["wedding", "corporate", "party"],
        contact: "orders@gourmetbites.com",
      },
      {
        id: "c14",
        name: "Homestyle Feasts",
        specialty: "Comforting and delicious home-style buffet.",
        price: "₹58,000",
        cost: 58000,
        eventType: ["wedding", "party", "gathering"],
        contact: "contact@homestylefeasts.com",
      },
      {
        id: "c4",
        name: "Continental Catering",
        specialty: "Classic dishes for large-scale events.",
        price: "₹50,000",
        cost: 50000,
        eventType: ["corporate"],
        contact: "info@continentalcatering.com",
      },
      {
        id: "c10",
        name: "Sushi & Sashimi Bar",
        specialty: "Live sushi station with a master chef.",
        price: "₹70,000",
        cost: 70000,
        eventType: ["corporate", "wedding"],
        contact: "sushi@bar.com",
      },
      {
        id: "c7",
        name: "Michelin Star Experience",
        specialty: "Curated menu by a renowned chef.",
        price: "₹95,000",
        cost: 95000,
        eventType: ["wedding", "corporate"],
        contact: "chef@michelin.com",
      },
      {
        id: "c15",
        name: "Green Plate Gourmet",
        specialty: "High-end, exclusively vegan culinary experiences.",
        price: "₹150,000",
        cost: 150000,
        eventType: ["wedding", "corporate"],
        contact: "contact@greenplategourmet.com",
      },
      {
        id: "c8",
        name: "Elaborate Food Stations",
        specialty: "Interactive live counters and bars.",
        price: "₹150,000",
        cost: 150000,
        eventType: ["wedding", "corporate"],
        contact: "events@foodstations.com",
      },
      {
        id: "c16",
        name: "Gourmet Artistry",
        specialty: "The finest ingredients, exquisitely presented.",
        price: "₹700,000",
        cost: 700000,
        eventType: ["wedding", "corporate"],
        contact: "contact@gourmetartistry.com",
      },
    ],
  },
  cakes_drinks: {
    title: "Cakes & Beverages",
    icon: "🍰",
    items: [
      {
        id: "cd1",
        name: "The Daily Grind Express",
        specialty: "Mobile coffee bar with professional baristas.",
        price: "₹14,000",
        cost: 14000,
        eventType: ["corporate", "wedding", "gathering"],
        contact: "contact@dailygrindexpress.com",
      },
      {
        id: "cd2",
        name: "Sweet Creations Patisserie",
        specialty: "Custom cakes, pastries, and dessert tables.",
        price: "₹15,000",
        cost: 15000,
        eventType: ["wedding", "party"],
        contact: "contact@sweetcreations.com",
      },
      {
        id: "cd3",
        name: "The Alchemist's Bar",
        specialty: "Expert mixologists and a stylish mobile bar setup.",
        price: "₹45,000",
        cost: 45000,
        eventType: ["wedding", "corporate", "party"],
        contact: "contact@alchemistsbar.com",
      },
    ],
  },
  decor: {
    title: "Decor & Styling",
    icon: "✨",
    items: [
      {
        id: "d9",
        name: "Streamers & Balloons",
        specialty: "Basic party decoration package.",
        price: "₹1,200",
        cost: 1200,
        eventType: ["party", "gathering"],
        contact: "contact@simpledecor.com",
      },
      {
        id: "d10",
        name: "Rental Centerpieces",
        specialty: "Affordable, elegant centerpieces for rent.",
        price: "₹3,000",
        cost: 3000,
        eventType: ["wedding", "corporate", "party"],
        contact: "rent@centerpieces.com",
      },
      {
        id: "d11",
        name: "Blossom & Twine",
        specialty: "Elegant and affordable decor solutions.",
        price: "₹8,000",
        cost: 8000,
        eventType: ["party", "gathering", "wedding"],
        contact: "contact@blossomtwine.com",
      },
      {
        id: "d4",
        name: "DIY Decor Kits",
        specialty: "Pre-packaged themes for you to set up.",
        price: "₹4,000",
        cost: 4000,
        eventType: ["party", "gathering"],
        contact: "kits@diydecor.com",
      },
      {
        id: "d12",
        name: "Inflated Imaginations",
        specialty: "Custom, large-scale balloon installations.",
        price: "₹9,000",
        cost: 9000,
        eventType: ["party", "corporate"],
        contact: "contact@inflatedimaginations.com",
      },
      {
        id: "d8",
        name: "Balloon Artistry",
        specialty: "Creative and grand balloon arrangements.",
        price: "₹9,000",
        cost: 9000,
        eventType: ["party"],
        contact: "art@balloons.com",
      },
      {
        id: "d2",
        name: "Boho Dreams",
        specialty: "Rustic, bohemian, and natural styling.",
        price: "₹12,000",
        cost: 12000,
        eventType: ["wedding", "party", "gathering"],
        contact: "style@bohodreams.com",
      },
      {
        id: "d13",
        name: "Fabric Fantasy",
        specialty: "Elegant drapery, linens, and fabric installations.",
        price: "₹20,000",
        cost: 20000,
        eventType: ["wedding", "corporate"],
        contact: "contact@fabricfantasy.com",
      },
      {
        id: "d5",
        name: "Thematic Creations",
        specialty: "Custom themes like Hollywood, Retro, etc.",
        price: "₹20,000",
        cost: 20000,
        eventType: ["corporate", "party"],
        contact: "themes@creations.com",
      },
      {
        id: "d1",
        name: "Elegant Designs",
        specialty: "Classic and sophisticated event decor.",
        price: "₹35,000",
        cost: 35000,
        eventType: ["wedding", "corporate"],
        contact: "design@elegant.com",
      },
      {
        id: "d14",
        name: "Crystal Carvings",
        specialty: "Stunning custom ice sculptures and bars.",
        price: "₹48,000",
        cost: 48000,
        eventType: ["wedding", "corporate"],
        contact: "contact@crystalcarvings.com",
      },
      {
        id: "d3",
        name: "Modern Visions",
        specialty: "Minimalist and contemporary aesthetics.",
        price: "₹55,000",
        cost: 55000,
        eventType: ["corporate", "party"],
        contact: "contact@modernvisions.com",
      },
      {
        id: "d15",
        name: "Petal & Stem Florists",
        specialty: "Bespoke floral design for any occasion.",
        price: "₹55,000",
        cost: 55000,
        eventType: ["wedding", "corporate"],
        contact: "contact@petalandstem.com",
      },
      {
        id: "d6",
        name: "Luxe Floral Arrangements",
        specialty: "Exotic flowers and grand floral structures.",
        price: "₹90,000",
        cost: 90000,
        eventType: ["wedding"],
        contact: "flowers@luxe.com",
      },
      {
        id: "d16",
        name: "Rustic Charm Designs",
        specialty: "High-end boutique decor with a rustic feel.",
        price: "₹110,000",
        cost: 110000,
        eventType: ["wedding"],
        contact: "contact@rusticcharm.com",
      },
      {
        id: "d7",
        name: "Grand Scale Productions",
        specialty: "Custom sets, lighting, and AV design.",
        price: "₹180,000",
        cost: 180000,
        eventType: ["wedding", "corporate"],
        contact: "productions@grandscale.com",
      },
      {
        id: "d17",
        name: "Luminous Projections",
        specialty: "Jaw-dropping 3D projection mapping on buildings or cakes.",
        price: "₹220,000",
        cost: 220000,
        eventType: ["wedding", "corporate"],
        contact: "contact@luminousprojections.com",
      },
      {
        id: "d18",
        name: "Opulent Occasions",
        specialty: "Ultimate luxury decor for the most lavish events.",
        price: "₹850,000",
        cost: 850000,
        eventType: ["wedding"],
        contact: "contact@opulentoccasions.com",
      },
    ],
  },
  photo_video: {
    title: "Photography & Video",
    icon: "📸",
    items: [
      {
        id: "pv1",
        name: "Snap Happy Booths",
        specialty: "Modern, interactive photo booths with fun props.",
        price: "₹18,000",
        cost: 18000,
        eventType: ["wedding", "party", "corporate"],
        contact: "contact@snaphappy.com",
      },
      {
        id: "pv2",
        name: "Pixel Perfect Moments",
        specialty: "Candid and traditional event photography.",
        price: "₹60,000",
        cost: 60000,
        eventType: ["wedding", "corporate", "party"],
        contact: "contact@pixelperfect.com",
      },
      {
        id: "pv3",
        name: "Aerial Perspectives",
        specialty: "Breathtaking drone photography and videography.",
        price: "₹70,000",
        cost: 70000,
        eventType: ["wedding", "corporate"],
        contact: "contact@aerialperspectives.com",
      },
      {
        id: "pv4",
        name: "Cinematic Tales",
        specialty: "High-quality, story-driven event videography.",
        price: "₹85,000",
        cost: 85000,
        eventType: ["wedding", "corporate"],
        contact: "contact@cinematictales.com",
      },
    ],
  },
  entertainment: {
    title: "Entertainment",
    icon: "🎭",
    items: [
      {
        id: "e10",
        name: "Karaoke Machine Setup",
        specialty: "Karaoke machine rental with mics and screen.",
        price: "₹3,500",
        cost: 3500,
        eventType: ["party"],
        contact: "sing@karaoke.com",
      },
      {
        id: "e7",
        name: "Caricature Artist",
        specialty: "Live drawings of guests for a fun keepsake.",
        price: "₹6,000",
        cost: 6000,
        eventType: ["party", "gathering"],
        contact: "draw@caricature.com",
      },
      {
        id: "e3",
        name: "Acoustic Harmonies",
        specialty: "Solo or duo acoustic performers.",
        price: "₹7,000",
        cost: 7000,
        eventType: ["wedding", "corporate", "gathering"],
        contact: "contact@acousticharmonies.com",
      },
      {
        id: "e4",
        name: "Mystic Magic",
        specialty: "Close-up and stage magic shows.",
        price: "₹9,000",
        cost: 9000,
        eventType: ["party", "gathering"],
        contact: "magic@mystic.com",
      },
      {
        id: "e11",
        name: "The Engaging Orator",
        specialty: "Professional Master of Ceremonies (MC) or host.",
        price: "₹19,000",
        cost: 19000,
        eventType: ["wedding", "corporate"],
        contact: "contact@engagingorator.com",
      },
      {
        id: "e12",
        name: "Mystic Marvels Entertainment",
        specialty: "High-energy magician and illusionist show.",
        price: "₹21,000",
        cost: 21000,
        eventType: ["party", "corporate"],
        contact: "contact@mysticmarvels.com",
      },
      {
        id: "e2",
        name: "DJ Pulse",
        specialty: "High-energy DJ for modern dance parties.",
        price: "₹22,000",
        cost: 22000,
        eventType: ["wedding", "party"],
        contact: "info@djpulse.com",
      },
      {
        id: "e13",
        name: "DJ Rhythmic Beats",
        specialty: "Versatile DJ for weddings and corporate events.",
        price: "₹30,000",
        cost: 30000,
        eventType: ["wedding", "party", "corporate"],
        contact: "contact@rhythmicbeats.com",
      },
      {
        id: "e14",
        name: "Dance Dynamics",
        specialty: "Choreography for sangeet, first dances, and flash mobs.",
        price: "₹26,000",
        cost: 26000,
        eventType: ["wedding", "party"],
        contact: "contact@dancedynamics.com",
      },
      {
        id: "e8",
        name: "String Quartet",
        specialty: "Classical and contemporary music for an elegant touch.",
        price: "₹40,000",
        cost: 40000,
        eventType: ["wedding", "corporate"],
        contact: "booking@stringquartet.com",
      },
      {
        id: "e1",
        name: "Groove Masters Band",
        specialty: "Live band playing pop, rock, and soul.",
        price: "₹60,000",
        cost: 60000,
        eventType: ["wedding", "corporate", "party"],
        contact: "booking@groovemasters.com",
      },
      {
        id: "e15",
        name: "The Harmony Collective",
        specialty: "A premium, multi-piece band for a concert-like experience.",
        price: "₹175,000",
        cost: 175000,
        eventType: ["wedding", "corporate"],
        contact: "contact@harmonycollective.com",
      },
      {
        id: "e6",
        name: "Celebrity Appearance",
        specialty: "Guest appearance by a local celebrity or artist.",
        price: "₹200,000",
        cost: 200000,
        eventType: ["wedding", "corporate"],
        contact: "talent@celebrity.com",
      },
      {
        id: "e16",
        name: "Celestial Sparks Pyrotechnics",
        specialty: "Professional, synchronized firework displays.",
        price: "₹300,000",
        cost: 300000,
        eventType: ["wedding", "corporate"],
        contact: "contact@celestialsparks.com",
      },
    ],
  },
  planning: {
    title: "Planning & Coordination",
    icon: "📋",
    items: [
      {
        id: "p1",
        name: "Sacred Vows Ceremonies",
        specialty: "Professional wedding officiant services.",
        price: "₹16,000",
        cost: 16000,
        eventType: ["wedding"],
        contact: "contact@sacredvows.com",
      },
      {
        id: "p2",
        name: "Seamless Day Events",
        specialty: "On-the-day coordination to ensure everything runs smoothly.",
        price: "₹42,000",
        cost: 42000,
        eventType: ["wedding", "corporate"],
        contact: "contact@seamlessday.com",
      },
      {
        id: "p3",
        name: "Grandeur Events & Co.",
        specialty: "Comprehensive, full-service event planning from start to finish.",
        price: "₹250,000",
        cost: 250000,
        eventType: ["wedding", "corporate"],
        contact: "contact@grandeurevents.com",
      },
    ],
  },
  beauty_style: {
    title: "Beauty & Style",
    icon: "💄",
    items: [
      {
        id: "bs1",
        name: "Intricate Henna by Aarti",
        specialty: "Traditional and modern henna/mehndi artistry.",
        price: "₹6,000",
        cost: 6000,
        eventType: ["wedding", "party"],
        contact: "contact@hennabyarti.com",
      },
      {
        id: "bs2",
        name: "Glamour by Priya",
        specialty: "Bridal and event makeup artist services.",
        price: "₹22,000",
        cost: 22000,
        eventType: ["wedding", "party"],
        contact: "contact@glamourbypriya.com",
      },
    ],
  },
  stationery: {
    title: "Stationery & Favors",
    icon: "🎁",
    items: [
      {
        id: "s1",
        name: "Ink & Grace Calligraphy",
        specialty: "Handwritten calligraphy for invitations and place cards.",
        price: "₹7,500",
        cost: 7500,
        eventType: ["wedding", "corporate"],
        contact: "contact@inkandgrace.com",
      },
      {
        id: "s2",
        name: "Memorable Tokens",
        specialty: "Custom party favors and gifts for guests.",
        price: "₹11,000",
        cost: 11000,
        eventType: ["wedding", "party", "corporate"],
        contact: "contact@memorabletokens.com",
      },
      {
        id: "s3",
        name: "The Gilded Quill",
        specialty: "Bespoke, luxury invitation design and printing.",
        price: "₹12,000",
        cost: 12000,
        eventType: ["wedding", "corporate"],
        contact: "contact@gildedquill.com",
      },
      {
        id: "s4",
        name: "Digital Invites & More",
        specialty: "Event websites, e-invites, and RSVP management.",
        price: "₹24,000",
        cost: 24000,
        eventType: ["wedding", "corporate", "party"],
        contact: "contact@digitalinvites.com",
      },
    ],
  },
  rentals_services: {
    title: "Rentals & Services",
    icon: "🚚",
    items: [
      {
        id: "rs1",
        name: "Tiny Treasures Rentals",
        specialty: "Rental of small decor items, props, and signage.",
        price: "₹4,000",
        cost: 4000,
        eventType: ["wedding", "party"],
        contact: "contact@tinytreasures.com",
      },
      {
        id: "rs2",
        name: "Helping Hands Hospitality",
        specialty: "Professional waiters, ushers, and event staff.",
        price: "₹32,000",
        cost: 32000,
        eventType: ["wedding", "corporate"],
        contact: "contact@helpinghands.com",
      },
      {
        id: "rs3",
        name: "Swift Valet",
        specialty: "Professional valet parking services for any venue.",
        price: "₹35,000",
        cost: 35000,
        eventType: ["wedding", "corporate"],
        contact: "contact@swiftvalet.com",
      },
      {
        id: "rs4",
        name: "The Gilded Plate",
        specialty: "Rental of premium tableware, cutlery, and glassware.",
        price: "₹38,000",
        cost: 38000,
        eventType: ["wedding", "corporate"],
        contact: "contact@gildedplate.com",
      },
      {
        id: "rs5",
        name: "Sit & Style Rentals",
        specialty: "Stylish furniture rental from chairs to lounge sets.",
        price: "₹50,000",
        cost: 50000,
        eventType: ["wedding", "corporate"],
        contact: "contact@sitandstyle.com",
      },
      {
        id: "rs6",
        name: "Classic Wheels Hire",
        specialty: "Rental of vintage and classic cars for transport.",
        price: "₹52,000",
        cost: 52000,
        eventType: ["wedding"],
        contact: "contact@classicwheels.com",
      },
      {
        id: "rs7",
        name: "Shield Security Solutions",
        specialty: "Professional security personnel for event safety.",
        price: "₹65,000",
        cost: 65000,
        eventType: ["wedding", "corporate"],
        contact: "contact@shieldsecurity.com",
      },
      {
        id: "rs8",
        name: "Royal Carriage Services",
        specialty: "Luxury transportation - limos, coaches, and high-end cars.",
        price: "₹75,000",
        cost: 75000,
        eventType: ["wedding", "corporate"],
        contact: "contact@royalcarriage.com",
      },
      {
        id: "rs9",
        name: "Aura AudioVisuals",
        specialty: "Professional sound systems, lighting, and projectors.",
        price: "₹90,000",
        cost: 90000,
        eventType: ["wedding", "corporate"],
        contact: "contact@auraav.com",
      },
      {
        id: "rs10",
        name: "Canvas Canopy Co.",
        specialty: "High-quality tents, marquees, and canopies for outdoor events.",
        price: "₹125,000",
        cost: 125000,
        eventType: ["wedding", "corporate", "party"],
        contact: "contact@canvascanopy.com",
      },
    ],
  },
}

export const checklists = {
  wedding: [
    "Finalize Guest List",
    "Send Invitations",
    "Book Photographer & Videographer",
    "Choose Wedding Attire",
    "Plan Ceremony Details",
    "Finalize Menu with Caterer",
    "Arrange Transportation",
    "Confirm with all Vendors",
  ],
  corporate: [
    "Define Event Goals & Objectives",
    "Set a Budget",
    "Select Venue",
    "Arrange Speakers/Presenters",
    "Plan Agenda/Schedule",
    "Send Invitations & Manage Registration",
    "Coordinate with AV/Technical Team",
    "Organize Catering",
  ],
  party: [
    "Choose a Theme",
    "Create Guest List",
    "Send out Invitations",
    "Plan Menu & Drinks",
    "Organize Music/Entertainment",
    "Buy Decorations",
    "Plan Party Activities/Games",
    "Confirm Venue",
  ],
  gathering: [
    "Decide on a Date & Time",
    "Invite Guests",
    "Plan a Simple Menu",
    "Arrange for Drinks",
    "Create a Music Playlist",
    "Tidy up the Space",
    "Ensure Enough Seating",
  ],
}
